# Generated by Django 4.1.5 on 2023-03-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flora', '0002_feedback_usermail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='usermail',
            new_name='mail',
        ),
        migrations.AddField(
            model_name='feedback',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
